### ISSUE TITLE
develop에서 42 intra oauth 시도시 500 오류

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#547]
### 재현 방법

프론트, 백엔드를 develop 브랜치에서 실행합니다.

프론트: 1be840e8df8f5db88760e02dd0d4a3178d222e9f
백엔드: e1b63f6f41a53dc69f93d45902e086fbf8873465

### 발생 위치

프론트엔드 dev 서버에서 42 intra로 로그인 시도시 500 오류와 함께 실패합니다.

### 추가 정보

```
2023-07-06 18:48:59:4859 http: GET /api/auth/oauth 302 482 - 3.144 ms

2023-07-06 18:49:00:490 error: Failed to obtain access token
 Error Stack: InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/home/scarf/repo/lib42/backend/node_modules/.pnpm/passport-oauth2@1.7.0/node_modules/passport-oauth2/lib/strategy.js:423:17)
    at /home/scarf/repo/lib42/backend/node_modules/.pnpm/passport-oauth2@1.7.0/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /home/scarf/repo/lib42/backend/node_modules/.pnpm/oauth@0.9.15/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/home/scarf/repo/lib42/backend/node_modules/.pnpm/oauth@0.9.15/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (node:events:511:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
2023-07-06 18:49:00:490 http: GET /api/auth/token?code=b02cd9c1102ec65bae02bebdd673806f29483742d4b581d0dbfc192aad8611f7 500 15 - 788.714 ms
```

**Comment by scarf005** [comment]
node 20버전 문제인것 같습니다 https://github.com/nodejs/node/issues/47822
